# Generated by Django 5.2.7 on 2025-10-17 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InjuryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_date', models.DateField(auto_now_add=True)),
                ('injury_date', models.DateField(null=True)),
                ('body_part', models.CharField(choices=[('HEAD', 'Head'), ('NECK', 'Neck'), ('SHOULDER', 'Shoulder'), ('ARM', 'Arm'), ('HAND', 'Hand'), ('CHEST', 'Chest'), ('BACK', 'Back'), ('HIP', 'Hip'), ('THIGH', 'Thigh'), ('KNEE', 'Knee'), ('LEG', 'Leg'), ('ANKLE', 'Ankle'), ('FOOT', 'Foot'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('diagnosis', models.CharField(max_length=255)),
                ('mechanism', models.CharField(blank=True, max_length=255)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], max_length=10)),
                ('imaging_required', models.BooleanField(default=False)),
                ('imaging_type', models.CharField(choices=[('XRAY', 'X-ray'), ('MRI', 'MRI'), ('CT', 'CT'), ('US', 'Ultrasound'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('imaging_details', models.CharField(blank=True, max_length=255)),
                ('treatment_given', models.TextField(blank=True)),
                ('recommended_followup', models.TextField(blank=True)),
                ('time_lost_days', models.IntegerField(blank=True, null=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('restrictions', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injury_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
    ]
