# Generated by Django 5.2.7 on 2025-10-22 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InjurySeverity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color_code', models.CharField(help_text='Hex color code (e.g., #FF0000)', max_length=7)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InjuryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InjuryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('injury_date', models.DateField()),
                ('reported_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RECOVERING', 'Recovering'), ('RECOVERED', 'Recovered'), ('CHRONIC', 'Chronic')], default='ACTIVE', max_length=20)),
                ('description', models.TextField()),
                ('symptoms', models.TextField(blank=True)),
                ('treatment', models.CharField(choices=[('REST', 'Rest'), ('PHYSIO', 'Physiotherapy'), ('SURGERY', 'Surgery'), ('MEDICATION', 'Medication'), ('OTHER', 'Other')], max_length=20)),
                ('treatment_notes', models.TextField(blank=True)),
                ('estimated_recovery_time', models.PositiveIntegerField(blank=True, help_text='Estimated recovery time in days', null=True)),
                ('actual_recovery_time', models.PositiveIntegerField(blank=True, help_text='Actual recovery time in days', null=True)),
                ('return_to_play_date', models.DateField(blank=True, null=True)),
                ('requires_surgery', models.BooleanField(default=False)),
                ('surgery_date', models.DateField(blank=True, null=True)),
                ('medical_clearance', models.BooleanField(default=False)),
                ('clearance_date', models.DateField(blank=True, null=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='injury_tracking.bodypart')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_injuries', to=settings.AUTH_USER_MODEL)),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='injury_tracking.injuryseverity')),
                ('injury_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='injury_tracking.injurytype')),
            ],
            options={
                'ordering': ['-injury_date'],
                'permissions': [('view_own_injuries', 'Can view own injuries'), ('view_team_injuries', 'Can view team injuries'), ('view_all_injuries', 'Can view all injuries')],
            },
        ),
        migrations.CreateModel(
            name='InjuryFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField()),
                ('notes', models.TextField()),
                ('status_update', models.CharField(choices=[('ACTIVE', 'Active'), ('RECOVERING', 'Recovering'), ('RECOVERED', 'Recovered'), ('CHRONIC', 'Chronic')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('injury', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='injury_tracking.injuryrecord')),
            ],
        ),
        migrations.CreateModel(
            name='InjuryAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveIntegerField()),
                ('total_injuries', models.PositiveIntegerField(default=0)),
                ('active_injuries', models.PositiveIntegerField(default=0)),
                ('recovered_injuries', models.PositiveIntegerField(default=0)),
                ('average_recovery_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('most_common_body_part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='injury_tracking.bodypart')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.team')),
                ('most_common_injury_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='injury_tracking.injurytype')),
            ],
            options={
                'unique_together': {('team', 'season_year')},
            },
        ),
        migrations.CreateModel(
            name='TeamRoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=50)),
                ('jersey_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roster', to='accounts.team')),
            ],
            options={
                'unique_together': {('team', 'player')},
            },
        ),
    ]
