# Generated by Django 6.0.6 on 2026-06-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injury_tracking', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryrecord',
            name='contact_type',
            field=models.CharField(choices=[('CONTACT', 'Contact'), ('NON_CONTACT', 'Non-Contact'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Whether the injury was caused by contact with another player', max_length=20),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='missed_games',
            field=models.PositiveIntegerField(default=0, help_text='Number of games missed due to this injury'),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='missed_practices',
            field=models.PositiveIntegerField(default=0, help_text='Number of practices missed due to this injury'),
        ),
    ]
