# Generated by Team 12 — COMP 8977 — Summer 2026
# Adds contact_type and missed_events fields to InjuryRecord
# Run with: python manage.py migrate

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Depends on the last migration Team 13 wrote for injury_tracking
        ('injury_tracking', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryrecord',
            name='contact_type',
            field=models.CharField(
                max_length=20,
                choices=[
                    ('CONTACT', 'Contact'),
                    ('NON_CONTACT', 'Non-Contact'),
                    ('OVERUSE', 'Overuse / Repetitive Strain'),
                    ('UNKNOWN', 'Unknown'),
                ],
                default='UNKNOWN',
                help_text=(
                    "Whether the injury resulted from contact with another player or object "
                    "(Contact), from the athlete's own movement with no external contact "
                    "(Non-Contact), from repetitive strain over time (Overuse), "
                    "or is unclassified (Unknown)."
                ),
            ),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='missed_games',
            field=models.PositiveIntegerField(
                null=True,
                blank=True,
                help_text="Number of official games missed due to this injury.",
            ),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='missed_practices',
            field=models.PositiveIntegerField(
                null=True,
                blank=True,
                help_text="Number of practices/training sessions missed due to this injury.",
            ),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='season_year',
            field=models.PositiveIntegerField(
                null=True,
                blank=True,
                help_text=(
                    "Academic season year this injury belongs to "
                    "(e.g. 2025 means the 2025–26 season). "
                    "Auto-populated from injury_date if left blank."
                ),
            ),
        ),
    ]
