# Generated by Django 6.0.6 on 2026-06-07 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification'),
        ('injury_tracking', '0003_add_contact_type_missed_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryrecord',
            name='self_reported',
            field=models.BooleanField(default=False, help_text='True if reported directly by the player (pending therapist review).'),
        ),
        migrations.AlterField(
            model_name='injuryrecord',
            name='contact_type',
            field=models.CharField(choices=[('CONTACT', 'Contact'), ('NON_CONTACT', 'Non-Contact'), ('OVERUSE', 'Overuse / Repetitive Strain'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text="Contact = caused by contact with another player or object. Non-Contact = athlete's own movement, no external contact. Overuse = repetitive strain over time. Unknown = not yet classified.", max_length=20),
        ),
        migrations.AlterField(
            model_name='injuryrecord',
            name='missed_practices',
            field=models.PositiveIntegerField(blank=True, help_text='Number of practices / training sessions missed due to this injury.', null=True),
        ),
        migrations.AlterField(
            model_name='injuryrecord',
            name='season_year',
            field=models.PositiveIntegerField(blank=True, help_text='Academic season this injury belongs to (e.g. 2025 = the 2025–26 season). Auto-populated from injury_date if left blank.', null=True),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField()),
                ('preferred_time_slot', models.CharField(choices=[('MORNING', 'Morning (9 AM - 12 PM)'), ('AFTERNOON', 'Afternoon (12 PM - 5 PM)'), ('EVENING', 'Evening (5 PM - 7 PM)')], max_length=20)),
                ('confirmed_datetime', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(limit_choices_to={'role': 'PLAYER'}, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='accounts.team')),
                ('therapist', models.ForeignKey(blank=True, help_text='Doctor / therapist assigned to handle the appointment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapist_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['preferred_date', 'created_at'],
                'indexes': [models.Index(fields=['player', 'status'], name='injury_trac_player__499a4c_idx'), models.Index(fields=['preferred_date'], name='injury_trac_preferr_f2feb7_idx')],
            },
        ),
    ]
