# Generated by Django 6.0.5 on 2026-06-30 18:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('injury_tracking', '0004_injuryrecord_self_reported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='injuryrecord',
            name='could_keep_playing',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('STOPPED_LATER', 'Stopped later')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='injury_context',
            field=models.CharField(blank=True, choices=[('PRACTICE', 'Practice'), ('GAME', 'Game'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='injury_nature',
            field=models.CharField(blank=True, choices=[('bruise', 'Bruise'), ('twist', 'Twist'), ('pull', 'Pull'), ('impact', 'Impact'), ('cut', 'Cut'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='pain_level',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='injuryrecord',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='injury_photos/'),
        ),
    ]
