# Generated by Django 5.2.7 on 2025-10-22 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_registration_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coaching_experience', models.PositiveIntegerField(blank=True, help_text='Years of coaching experience', null=True)),
                ('specialization', models.CharField(blank=True, help_text='Coaching specialization', max_length=100)),
                ('certification', models.CharField(blank=True, help_text='Coaching certifications', max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_license', models.CharField(blank=True, help_text='Medical license number', max_length=100)),
                ('specialization', models.CharField(blank=True, help_text='Medical specialization', max_length=100)),
                ('years_experience', models.PositiveIntegerField(blank=True, help_text='Years of medical experience', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailRoleMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_pattern', models.CharField(help_text='Email domain (e.g., @lancer.com) or specific email', max_length=255)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('COACH', 'Coach'), ('DOCTOR', 'Doctor'), ('PLAYER', 'Player')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('team', models.ForeignKey(blank=True, help_text='Auto-assign team (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.team')),
            ],
        ),
    ]
