# Generated by Django 5.2.7 on 2025-10-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_address_customuser_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='academic_restrictions',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='alternate_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='citizenship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='club_team_coach_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='completed_18_credits_last_year',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('NA', 'N/A')], max_length=10),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='faculty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='family_member_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='family_member_oua_usports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='graduating_this_year',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='height_feet',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='height_inches',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='high_school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='high_school_coach_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='hometown',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='local_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='local_postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='local_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='local_street_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='permanent_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='permanent_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='permanent_postal_zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='permanent_province_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='permanent_street_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='photo_id',
            field=models.ImageField(blank=True, null=True, upload_to='player_ids/'),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='position_event',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='previous_club_team',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='program_of_study',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='registered_9_credits_per_term',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=10),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='school_type_last_year',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='sport_gender_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='student_status',
            field=models.CharField(blank=True, choices=[('UNDERGRADUATE', 'Undergraduate'), ('GRADUATE', 'Graduate'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='weight_lbs',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='year_of_study',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
